#!/usr/bin/env python3
import json
from pathlib import Path

from kython.kompress import open as kopen

OUTPUT_DIR = Path(__file__).absolute().parent.parent / 'content' / 'generated'

POSTS = {
    'ayt5cu': 'takeout-data-gone.md',
}


def render(sub):
    # tags -- external
    # summary: ??? manual maybe?
    # upid: ??? manual?
    # date: ??? format manually I guess, but could include time too now
    title = sub['title']
    dts = sub['created_utc'] # TODO format it.. not sure what's about tz
    '/' + sub['subreddit_name_prefixed']
    url = sub['url'] # TODO what's the difference with permalink?
    content = sub['selftext']
    # url: ?? put in title? or summary? or smth else?
    post = f"""
---
title: {title}
date: {dts}
---
Reddit link: {url}

{content}
""".lstrip()
    return post


def main():
    assert OUTPUT_DIR.exists()

    with kopen(max(Path('/L/backups/reddit').glob('*.json.xz'))) as fo:
        j = json.load(fo)

    subs = {s['id']: s for s in j['submissions']}
    for pid, out in POSTS.items():
        print(f"Rendering: {pid} -> {out}")
        sub = subs[pid]
        (OUTPUT_DIR / out).write_text(render(sub))

if __name__ == '__main__':
    main()
