#!/usr/bin/env python3
"""
Render referrers as a HTML table so I can see where my stuff is posted.
"""
from pathlib import Path

import pandas as pd # type: ignore

from process_logs import get_dataframe

# -1 for infinite
# TODO percentile??


less_prio = {
    'reddit.com',
    'lobste.rs',
    'news.ycombinator.com',
}

def run(*, access_log, exclude):
    if exclude is None:
        exclude = set()
    else:
        res = {}
        exec(exclude.read_text(), res)
        exclude = res['EXCLUDE']


    pd.set_option('display.max_colwidth', 200)

    df = get_dataframe(access_log)
    df = df[~df['error'].notnull()]

    # TODO filter reddit/hn somehow? or just sort to display in the bottom?
    boring_ref = (df['refferer'] == '-') | df['refferer'].str.contains('|'.join(exclude))
    # TODO dynamic sorting for pandas would be nice?
    rt = df[~boring_ref]
    rt = rt.sort_values(by=[
        'refferer',
        'dt',
    ], ascending=False)[[
        'dt',
        'url',
        'refferer',
    ]]
    return rt


def main():
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument('--access-log', type=Path, required=True)
    p.add_argument('--html', type=Path)
    p.add_argument('--exclude', type=Path)
    args = p.parse_args()
    html = args.html

    ref_table = run(access_log=args.access_log, exclude=args.exclude)
    if html is not None:
        html.write_text(ref_table.to_html())
    else:
        print(ref_table)


if __name__ == '__main__':
    main()
