#!/usr/bin/env python3
from pathlib import Path
from subprocess import run


# TODO FIXME cooperate with main script for less duplication
intermediate = Path('intermediate')


# TODO !! implement a test for this (all of params)
def search(*args):
    res = run([
        'rg',
        '--follow',
        '-i',
        *args,
    ])
    if res.returncode == 1:
        return # ok, nothin is found
    else:
        raise RuntimeError(res)


from checks import WORD_CHECKS
def check(path: Path):
    print(f"checking {path}")
    for x in WORD_CHECKS:
        search(
            '--word-regexp',
            x,
            path,
        )

    import orgparse
    ts = orgparse.date.TIMESTAMP_RE
    for line in path.read_text().splitlines():
        assert not ts.search(line), line


def main():
    # TODO not sure about org?
    for f in intermediate.glob('**/*.org'):
        check(f)


if __name__ == '__main__':
    main()
