#!/usr/bin/env python3
from pathlib import Path
from subprocess import check_call

this = Path(__file__).absolute()

def beepb00p(*args):
    bin = '/L/soft/beepb00p/site'
    check_call([
        bin,
        *args,
    ], cwd=this.parent)


# run beepb00p watch --no-server (how to make sure it's not buffering output?)
# if 'Cache corrupt' in output, warn somehow (e.g. ntfy to start with?)
# every night, just restart and rebuild?

# shit...
# Removing _site...
# beepb00p: _site: removeDirectoryRecursive: inappropriate type (not a directory)

def main():
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument('--setup', action='store_true')
    args = p.parse_args()

    if args.setup:
        from kython.ksystemd import setup
        setup(
            unit_name='beepb00p.service',
            exec_start=str(this),
        )
        return

    beepb00p('clean')
    beepb00p('watch', '--no-server')

# TODO use asyncio?

if __name__ == '__main__':
    main()
