#!/usr/bin/env python3
from pathlib import Path
from subprocess import check_call

cwd = Path(__file__).absolute().parent

def beepb00p(*args):
    bin = '/L/soft/beepb00p/site'
    check_call([
        bin,
        *args,
    ], cwd=cwd)


# run beepb00p watch --no-server (how to make sure it's not buffering output?)
# if 'Cache corrupt' in output, warn somehow (e.g. ntfy to start with?)
# every night, just restart and rebuild?

# shit...
# Removing _site...
# beepb00p: _site: removeDirectoryRecursive: inappropriate type (not a directory)

# TODO need to start via systemd?
def main():
    beepb00p('clean')
    beepb00p('watch', '--no-server')

# TODO use asyncio?

if __name__ == '__main__':
    main()
