* Lisbon notes
-- TODO pandoc lisbon.org -s -o lisbon.html ok that works; also use pandoc -D html for help..
-- pandoc lisbon.org -s -o lisbon.html --metadata author='Dima'
  
        -- compile $ pandocCompiler -- WithTransform def (def {
                                 --            writerVariables = [("author", "Dima")],
                                 --            writerTableOfContents = True

                                 
          -- return res
          -- return $ writePandoc pandoc
        -- compile $ do
        --   body <- getResourceBody
        --   -- traceShowM body
        --   pd <- readPandoc body
        --   traceShowM pd
        --   let wp = writePandoc pd 
        --   -- right ok, so it's got meta in Pandoc thing.

* stack build && stack exec site rebuild
* TODO [2019-05-07 Tue 20:27] rerender regularly so I could fix typos etc?
Can I base in on or perhaps manual inotify or something?? use folder differen than _site for output?

* TODO [2019-05-07 Tue 21:33] shit, org mode generates some random ids every time
  
* TODO [2019-05-09 Thu 21:59] for sufs, would be good to have a special 'github' type of post? not sure how to cache local/offline copy... or just need to merge md files
* TODO [#C] [2019-05-09 Thu 22:01] add importance, so it's easier to skip over not necessarily interesting stuff (like sufs)
