#!/bin/bash -eu
cd "$(dirname "$0")"

misc/poke-symlinks.py 'content' &
SH_PID="$!"

function cleanup {
    echo "killing poke-symlinks $SH_PID"
    kill "$SH_PID"
}

trap cleanup INT TERM EXIT

site="${SITE_COMMAND:-stack exec site}"
# eh, I'd prefer exec call here, but doesn't work with trap
# https://stackoverflow.com/a/24112832/706389 that doesn't help either
$site --verbose watch "$@"
