#!/bin/bash -eux
cd "$(dirname "$0")"

curl 'https://raw.githubusercontent.com/twitter/twemoji/gh-pages/v/12.1.3/svg/1f916.svg' -o robot-face.svg
# TODO eh. not sure if should use ico? or maybe just blob?
inkscape -z -w 180 -h 180 -e robot-face.png robot-face.svg

# white background; otherwise it's black
convert -background white -alpha remove -alpha off \
  robot-face.png robot-face.jpg
