#!/usr/bin/env python3
from datetime import datetime
import json
from pathlib import Path

import pytz

from kython.kompress import open as kopen

OUTPUT_DIR = Path(__file__).absolute().parent.parent / 'content' / 'generated'

POSTS = {
    'ayt5cu': 'takeout-data-gone.md',
}


def render(sub):
    # tags -- external
    # summary: ??? manual maybe?
    # upid: ??? manual?
    # date: ??? format manually I guess, but could include time too now
    title = sub['title']
    url = sub['url'] # TODO what's the difference with permalink?
    content = sub['selftext']

    ts = sub['created_utc']
    dt = datetime.fromtimestamp(ts, tz=pytz.utc)
    dts = dt.strftime('%B %e, %Y')
    '/' + sub['subreddit_name_prefixed']
    # url: ?? put in title? or summary? or smth else?
    # TODO not sure if we necessarily wanna reuse the title...
    # title: {title}
    post = f"""
---
date: {dts}
---
This is a [crosspost]({url}) from Reddit.

{content}
""".lstrip()
    return post


def main():
    assert OUTPUT_DIR.exists()

    with kopen(max(Path('/L/backups/reddit').glob('*.json.xz'))) as fo:
        j = json.load(fo)

    subs = {s['id']: s for s in j['submissions']}
    for pid, out in POSTS.items():
        print(f"Rendering: {pid} -> {out}")
        sub = subs[pid]
        (OUTPUT_DIR / out).write_text(render(sub))

if __name__ == '__main__':
    main()

# TODO use my. package
# TODO not sure if I really need it? 
